backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections: 
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Description", name: "description", widget: "string"}
    - {label: "Author", name: "author", widget: "string"}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Tags", name: "tags", widget: "list", default: ["post"] }
    - {label: "Featured Image", name: "image", widget: "string"}
    - {label: "Image caption", name: "imageAlt", widget: "string"}
    - {label: "Blog", name: "body", widget: "markdown"}